{% set name = "pyequib" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyequib-{{ version }}.tar.gz
  sha256: dab3eb4e99d85768673ed30ac90f0dae809bbb29de78cc5308f74cc1716798a9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - numpy >=1.17
    - scipy >=1.2
    - atomneb >=0.2
  run:
    - python >=3.8
    - numpy >=1.17
    - scipy >=1.2
    - atomneb >=0.2

test:
  imports:
    - pyequib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/equib/pyEQUIB
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: 'pyEQUIB: Python Package for Plasma Diagnostics and Abundance Analysis'
  dev_url: https://github.com/equib/pyEQUIB
  doc_url: https://pypi.python.org/pypi/pyequib

extra:
  recipe-maintainers:
    - danehkar
